### PR TITLE
adding chef-rightscale-plugin

### PR DESCRIPTION
**Pull request by rshade**
@cdwilhelm thoughts?

### CODE REVIEW

**Comment by rshade** [comment]
@rgeyer @gonzalez @adamalex thoughts?

**Review by adamalex — APPROVED** [review]
Pretty slick, @rshade !

**Comment by cdwilhelm** [comment]
I think this is cool.  I think we should put the rightscale ohai plugin into a gem and install the gem instead of using an attachment.  The reason I like that approach is mainly for the source control of the plugin, and then we can use it in other scripts too.

**Comment by rshade** [comment]
Can you describe the other use-cases? How it would install, and how it would add more source control then this methods?

**Comment by rshade** [comment]
we could create an ohai-plugin-cookbook, https://learn.chef.io/tutorials/build-an-ohai-plugin/, that seems like a lot of overkill for this, but it seems to be the "chef way", it just means all our cookbooks have to depend on this one.

**Comment by cdwilhelm** [comment]
@rshade I forgot the file was in github as a right_st server template.  I don't know other use cases.  so we can deal with that later if it comes up.

**Pull request merged**
